# Generated by Django 5.2.1 on 2025-06-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='contact_number',
            field=models.CharField(default='N/A', help_text='WhatsApp or mobile number', max_length=20),
            preserve_default=False,
        ),
    ]
